export { assetPaths, hasAssetPath } from "./assets";
export {
  friendMascots,
  getFriendById,
  getFriendCorrespondence,
  getFriendLocationLabel,
  getFriendMascots,
  mockFriends,
} from "./friends";
export {
  getInventoryItemsByCategory,
  getInventorySummary,
  inventoryCategories,
  mockInventoryItems,
} from "./inventory";
export { currentPlayer, getDeliveryById, getMascotById, nuvemDelivery, starterMascots } from "./mockData";
export {
  createMapPlaceLabelsGeoJson,
  createDeliveryRouteGeoJson,
  createRouteRewardsGeoJson,
  getPetMapPosition,
  getRouteRewardDiscoveries,
  interpolateCoordinates,
  toLngLat,
  type MapPlaceLabel,
  type MapPlaceLabelKind,
  type PetMapPosition,
  type RouteRewardDiscovery,
  type RouteRewardKind,
  type TravelLeg,
} from "./mapTravel";
export { createMockRewardFromDelivery, initialMockInventory } from "./rewards";
export { useRewardCollectionData } from "./useRewardCollectionData";
export {
  correspondenceOptions,
  createMockDeliveryFromSelection,
  createDefaultCorrespondenceContent,
  estimateMascotSpeedKmh,
  getCorrespondenceById,
  getCorrespondenceContentCount,
  getFriendCoordinates,
  isCorrespondenceContentValid,
  LETTER_MAX_CHARACTERS,
  mockPostcardOptions,
  mockStickerOptions,
  POSTCARD_MAX_CHARACTERS,
  STICKER_MAX_SELECTION,
} from "./sendFlow";
export {
  clampProgress,
  DEFAULT_GAME_SPEED_MULTIPLIER,
  estimateTravelDurationHours,
  formatRemainingTime,
  getDeliveryStatus,
  getTravelProgress,
  haversineDistanceKm,
} from "./travel";
export type {
  Coordinates,
  CorrespondenceContent,
  CorrespondenceOption,
  CorrespondenceType,
  Delivery,
  DeliveryStatus,
  EquipmentItem,
  EquipmentRarity,
  EquipmentType,
  FriendMascotPreview,
  FriendLocation,
  FriendProfile,
  GiftContentPlaceholder,
  InventoryCategory,
  InventoryItem,
  LetterContent,
  Mascot,
  MascotAppearance,
  MascotAttributeSet,
  MascotTrait,
  Player,
  PostcardContent,
  PostcardVariant,
  DeliveryReward,
  RewardItem,
  RewardRarity,
  ReceivedCorrespondencePreview,
  SendFlowSelection,
  Skill,
  StickerContent,
} from "./types";
