export { assetPaths, hasAssetPath } from "./assets";
export {
  friendMascots,
  getFriendById,
  getFriendCorrespondence,
  getFriendLocationLabel,
  getFriendMascots,
  mockFriends,
} from "./friends";
export {
  filterInventoryItemsByCategory,
  getInventoryCategoryCounts,
  getInventoryItemsByCategory,
  getInventorySummary,
  inventoryCategories,
  mockInventoryItems,
} from "./inventory";
export { currentPlayer, getDeliveryById, getMascotById, nuvemDelivery, starterMascots } from "./mockData";
export {
  createMapPlaceLabelsGeoJson,
  createDeliveryRouteGeoJson,
  createRouteRewardDiscoveries,
  createRouteRewardsGeoJson,
  getDistanceFromPointToRouteKm,
  getEligibleRouteRewards,
  getPetMapPosition,
  getRouteRewardDiscoveries,
  getRouteRewardProgress,
  interpolateCoordinates,
  mockRouteRewardPoints,
  toLngLat,
  type MapPlaceLabel,
  type MapPlaceLabelKind,
  type PetMapPosition,
  type RouteRewardDiscovery,
  type RouteRewardKind,
  type RouteRewardPoint,
  type RouteRewardRegionKind,
  type TravelLeg,
} from "./mapTravel";
export {
  createPostalTrafficGeoJson,
  getNearbyPostalTrafficPets,
  getPostalTrafficLabel,
  getPostalTrafficPetPosition,
  mockPostalTrafficPets,
  type PostalTrafficPet,
  type PostalTrafficPetSnapshot,
  type PostalTrafficRouteSnapshot,
  type PostalTrafficVisibility,
} from "./postalTraffic";
export { createMockRewardFromDelivery, initialMockInventory } from "./rewards";
export { useInventoryData } from "./useInventoryData";
export { useRewardCollectionData } from "./useRewardCollectionData";
export {
  correspondenceOptions,
  createMockDeliveryFromSelection,
  createDefaultCorrespondenceContent,
  estimateMascotSpeedKmh,
  getCorrespondenceById,
  getCorrespondenceContentCount,
  getFriendCoordinates,
  isCorrespondenceContentValid,
  LETTER_MAX_CHARACTERS,
  mockPostcardOptions,
  mockStickerOptions,
  POSTCARD_MAX_CHARACTERS,
  STICKER_MAX_SELECTION,
} from "./sendFlow";
export {
  clampProgress,
  DEFAULT_GAME_SPEED_MULTIPLIER,
  estimateTravelDurationHours,
  formatRemainingTime,
  getDeliveryStatus,
  getTravelProgress,
  haversineDistanceKm,
} from "./travel";
export type {
  Coordinates,
  CorrespondenceContent,
  CorrespondenceOption,
  CorrespondenceType,
  Delivery,
  DeliveryStatus,
  EquipmentItem,
  EquipmentRarity,
  EquipmentType,
  FriendMascotPreview,
  FriendLocation,
  FriendProfile,
  GiftContentPlaceholder,
  InventoryCategory,
  InventoryItem,
  LetterContent,
  Mascot,
  MascotAppearance,
  MascotAttributeSet,
  MascotTrait,
  Player,
  PostcardContent,
  PostcardVariant,
  DeliveryReward,
  RewardItem,
  RewardRarity,
  ReceivedCorrespondencePreview,
  SendFlowSelection,
  Skill,
  StickerContent,
} from "./types";
