import type { MascotFlightPreview, MascotFlightState, PrestigeBorder } from "../../game/types";
import type { TranslationKey } from "../../i18n";
import { getSupabaseClient } from "./client";

export type { MascotFlightPreview, MascotFlightState, PrestigeBorder } from "../../game/types";

export function mapMascotFlightState(data:unknown):MascotFlightState|undefined { if(!data||typeof data!=="object"||Array.isArray(data))return;const v=data as Record<string,unknown>;if(typeof v.level!=="number"||typeof v.xp!=="number"||typeof v.nextLevelXp!=="number"||typeof v.maxOneWayKm!=="number"||typeof v.naturalSlots!=="number"||!Array.isArray(v.borders))return;return{level:v.level,xp:v.xp,nextLevelXp:v.nextLevelXp,maxOneWayKm:v.maxOneWayKm,naturalSlots:v.naturalSlots,functionalCapReached:v.functionalCapReached===true,selectedBorderKey:typeof v.selectedBorderKey==="string"?v.selectedBorderKey:undefined,borders:v.borders.flatMap(item=>{if(!item||typeof item!=="object"||Array.isArray(item))return[];const b=item as Record<string,unknown>;return typeof b.catalogKey==="string"&&typeof b.minimumLevel==="number"&&typeof b.nameKey==="string"&&typeof b.descriptionKey==="string"&&typeof b.assetKey==="string"?[{catalogKey:b.catalogKey,minimumLevel:b.minimumLevel,nameKey:b.nameKey as TranslationKey,descriptionKey:b.descriptionKey as TranslationKey,assetKey:b.assetKey,unlocked:b.unlocked===true,selected:b.selected===true}]:[]} )};}
export function mapMascotFlightPreview(data:unknown):MascotFlightPreview|undefined {if(!data||typeof data!=="object"||Array.isArray(data))return;const v=data as Record<string,unknown>;const f=v.familiarity;if(v.rulesVersion!==58||typeof v.distanceKm!=="number"||typeof v.eligible!=="boolean"||typeof v.maxOneWayKm!=="number"||typeof v.naturalSlots!=="number"||!f||typeof f!=="object"||Array.isArray(f))return;const x=f as Record<string,unknown>;if(!["new","known","familiar","mastered"].includes(String(x.state))||typeof x.completedCount!=="number"||typeof x.speedMultiplier!=="number")return;return{rulesVersion:58,distanceKm:v.distanceKm,eligible:v.eligible,requiredLevel:typeof v.requiredLevel==="number"?v.requiredLevel:undefined,maxOneWayKm:v.maxOneWayKm,naturalSlots:v.naturalSlots,routePairKey:typeof v.routePairKey==="string"?v.routePairKey:undefined,familiarity:{state:x.state as MascotFlightPreview["familiarity"]["state"],completedCount:x.completedCount,speedMultiplier:x.speedMultiplier,nextAt:typeof x.nextAt==="number"?x.nextAt:undefined}};}
export async function fetchMascotFlightState(mascotId:string){const client=getSupabaseClient();if(!client)return;const{data,error}=await client.rpc("get_mascot_flight_state",{target_mascot_id:mascotId});if(error)throw error;return mapMascotFlightState(data);}
export async function previewMascotFlight(mascotId:string,profileId:string){const client=getSupabaseClient();if(!client)return;const{data,error}=await client.rpc("preview_mascot_flight",{target_mascot_id:mascotId,target_profile_id:profileId});if(error)throw error;return mapMascotFlightPreview(data);}
export async function selectMascotPrestigeBorder(mascotId:string,catalogKey:string){const client=getSupabaseClient();if(!client)throw new Error("Supabase unavailable");const{error}=await client.rpc("select_mascot_prestige_border",{target_mascot_id:mascotId,target_border_catalog_key:catalogKey});if(error)throw error;}
