import { useEffect, useId, useRef, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import { assetKeys, postmarkColors, type OfficialAssetKey, type PostmarkColorId, type PostmarkModelId } from "../../game";
import { useTranslation } from "../../i18n";
import { AssetImage } from "./AssetImage";
import { LetterPaper, type LetterPaperProps } from "./LetterDialog";
import styles from "./PostalCorrespondence.module.css";

export type PostalDensity = "preview" | "compact" | "reader";
export type PostalFinishing = { stampAssetKey?: OfficialAssetKey; postmark?: { city:string; country:string; date:string; model:PostmarkModelId; color:PostmarkColorId; stampedAt?:string; timeZone?:string; dateSource?:"origin-local-v1"|"utc-fallback-v1" } };
const densityClass=(density:PostalDensity)=>`${styles.correspondence} ${styles[density]}`;

export function PostalPostmark({postmark,showLabel=false}:{postmark?:PostalFinishing["postmark"];showLabel?:boolean}){
  const {locale,t}=useTranslation(); const pathId=useId().replace(/:/g,""); if(!postmark)return null;
  const ink=postmarkColors.find((option)=>option.id===postmark.color)?.value??postmarkColors[0].value;
  const date=new Date(`${postmark.date}T12:00:00Z`); const valid=!Number.isNaN(date.getTime());
  const classicDate=valid?new Intl.DateTimeFormat(locale,{day:"2-digit",month:"2-digit",year:"2-digit",timeZone:"UTC"}).format(date):postmark.date;
  const parts=valid?new Intl.DateTimeFormat(locale,{day:"2-digit",month:"short",timeZone:"UTC"}).formatToParts(date):[];
  const day=parts.find((part)=>part.type==="day")?.value??"--"; const month=(parts.find((part)=>part.type==="month")?.value??"---").replace(/\./g,"").toLocaleUpperCase(locale);
  const year=valid?new Intl.DateTimeFormat(locale,{year:"numeric",timeZone:"UTC"}).format(date):"----"; const routeDate=`${day} ${month}`; const wingDate=`${day} ${month} ${year}`;
  const city=postmark.city.toLocaleUpperCase(locale); const country=postmark.country.toLocaleUpperCase(locale);
  return <figure className={styles.postmarkPreview} style={{"--postmark-color":ink} as CSSProperties}><div className={styles.postmarkImpression} data-model={postmark.model}>
    {postmark.model==="route"?<svg aria-label={`${country}, ${city}, ${routeDate}`} className={`${styles.postmarkSeal} ${styles.routePostmarkSeal}`} role="img" viewBox="0 0 200 200"><path className={styles.routePostmarkOuter} d="M100 7 L191 187 L9 187 Z"/><path className={styles.routePostmarkInner} d="M100 22 L181 180 L19 180 Z"/><path className={styles.routePostmarkMainStar} d="M100 38 l5 10 11 2-8 8 2 11-10-5-10 5 2-11-8-8 11-2z"/><circle className={styles.routePostmarkSmallStar} cx="70" cy="111" r="4"/><circle className={styles.routePostmarkSmallStar} cx="100" cy="111" r="4"/><circle className={styles.routePostmarkSmallStar} cx="130" cy="111" r="4"/><text className={styles.routePostmarkDate} x="100" y="88">{routeDate}</text><text className={styles.routePostmarkCity} x="100" y="137">{city}</text><path className={styles.routePostmarkRule} d="M39 147 H161"/><text className={styles.routePostmarkCountry} x="100" y="174">{country}</text></svg>:
    postmark.model==="wing"?<svg aria-label={`${country}, ${city}, ${wingDate}`} className={`${styles.postmarkSeal} ${styles.wingPostmarkSeal}`} role="img" viewBox="0 0 220 180"><rect className={styles.wingPostmarkPerforation} height="164" rx="2" width="204" x="8" y="8"/><rect className={styles.wingPostmarkFrame} height="154" width="194" x="13" y="13"/><text className={styles.wingPostmarkCity} x="110" y="52">{city}</text><text className={styles.wingPostmarkCountry} x="110" y="82">★ {country} ★</text><text className={styles.wingPostmarkDate} x="110" y="112">{wingDate}</text><path className={styles.wingPostmarkRule} d="M14 126 H206"/><text className={styles.wingPostmarkLabel} x="110" y="153">{t("send.postalFinishing.airMail").toLocaleUpperCase(locale)}</text></svg>:
    <><svg aria-label={`${country}, ${city}, ${classicDate}`} className={styles.postmarkSeal} role="img" viewBox="0 0 200 200"><defs><path d="M 28 100 A 72 72 0 0 1 172 100" id={`${pathId}-country`}/><path d="M 26 108 A 74 74 0 0 0 174 108" id={`${pathId}-city`}/></defs><circle cx="100" cy="100" r="91"/><circle cx="100" cy="100" r="84"/><circle cx="100" cy="100" r="58"/><text className={styles.postmarkArcText}><textPath href={`#${pathId}-country`} startOffset="50%" textAnchor="middle">{country}</textPath></text><text className={`${styles.postmarkArcText} ${styles.postmarkCityText}`}><textPath href={`#${pathId}-city`} startOffset="50%" textAnchor="middle">{city}</textPath></text><path className={styles.postmarkDateRule} d="M43 88 H157 M43 114 H157"/><text className={styles.postmarkDateText} x="100" y="106">{classicDate}</text></svg><svg aria-hidden="true" className={styles.postmarkWaves} viewBox="0 0 120 42"><path d="M2 7 C14 0 24 14 36 7 S58 0 70 7 S94 14 118 7"/><path d="M2 21 C14 14 24 28 36 21 S58 14 70 21 S94 28 118 21"/><path d="M2 35 C14 28 24 42 36 35 S58 28 70 35 S94 42 118 35"/></svg></>}
  </div>{showLabel?<figcaption>{t(`send.postalFinishing.models.${postmark.model}`)}</figcaption>:null}</figure>;
}

export function PostalFinishingView({finishing}:{finishing?:PostalFinishing}){return <span aria-hidden="true" className={styles.finishing}><AssetImage alt="" assetKey={finishing?.stampAssetKey??assetKeys.stamps.default} className={styles.stamp}><i/></AssetImage><span className={styles.postmarkPlacement}><PostalPostmark postmark={finishing?.postmark}/></span></span>}

type EnvelopeProps={density?:PostalDensity;finishing?:PostalFinishing;recipientLabel?:string;recipientTitle?:string;senderLabel?:string;senderLocation?:string;senderTitle?:string;openLabel?:string;onOpen?:()=>void};
export function PostalEnvelope({density="preview",finishing,recipientLabel,recipientTitle,senderLabel,senderLocation,senderTitle,openLabel,onOpen}:EnvelopeProps){const content=<><PostalFinishingView finishing={finishing}/><span className={styles.recipient}><small>{recipientTitle}</small><strong>{recipientLabel}</strong></span><span className={styles.sender}><small>{senderTitle}</small><strong>{senderLabel}</strong><em>{senderLocation}</em></span></>;return onOpen?<button aria-label={openLabel} className={`${densityClass(density)} ${styles.envelope}`} onClick={onOpen} type="button">{content}</button>:<div className={`${densityClass(density)} ${styles.envelope}`}>{content}</div>}

type PostcardProps={density?:PostalDensity;interactive?:boolean;frontAssetKey?:OfficialAssetKey;frontAlt:string;message?:string;finishing?:PostalFinishing;senderName?:string;deliveredBy?:string;originTitle?:string;originLabel?:string;destinationTitle?:string;destinationLabel?:string;flipLabel:string};
export function PostalPostcard({density="preview",interactive=true,frontAssetKey,frontAlt,message,finishing,senderName,deliveredBy,originTitle,originLabel,destinationTitle,destinationLabel,flipLabel}:PostcardProps){const [back,setBack]=useState(false);const content=<span className={`${styles.postcardInner} ${back?styles.backVisible:""}`}><span className={`${styles.postcardFace} ${styles.postcardFront}`}>{frontAssetKey?<AssetImage alt={frontAlt} assetKey={frontAssetKey}><i/></AssetImage>:<span className={styles.missingArt}>{frontAlt}</span>}</span><span className={`${styles.postcardFace} ${styles.postcardBack}`}><span className={styles.postcardMessage}>{message}</span><span className={styles.postcardDetails}><PostalFinishingView finishing={finishing}/><strong>{senderName}</strong><span>{deliveredBy}</span><dl><div><dt>{originTitle}</dt><dd>{originLabel}</dd></div><div><dt>{destinationTitle}</dt><dd>{destinationLabel}</dd></div></dl></span></span></span>;return interactive?<button aria-label={flipLabel} aria-pressed={back} className={`${densityClass(density)} ${styles.postcard}`} onClick={()=>setBack((value)=>!value)} type="button">{content}</button>:<span className={`${densityClass(density)} ${styles.postcard}`}>{content}</span>}

export function PostalStickerSheet({density="preview",stickers,finishing}:{density?:PostalDensity;stickers:Array<{assetKey:OfficialAssetKey;label?:string}>;finishing?:PostalFinishing}){return <div className={`${densityClass(density)} ${styles.stickerSheet}`}><PostalFinishingView finishing={finishing}/><span className={styles.stickers}>{stickers.map((sticker,index)=><figure key={`${sticker.assetKey}-${index}`}><AssetImage alt={sticker.label??""} assetKey={sticker.assetKey}><i/></AssetImage>{sticker.label?<figcaption>{sticker.label}</figcaption>:null}</figure>)}</span></div>}

export function PostalLetterReader({backLabel,envelope,letter}: {backLabel:string;envelope:Omit<EnvelopeProps,"density"|"onOpen">;letter:LetterPaperProps}){const [sheetVisible,setSheetVisible]=useState(false);return <section className={styles.letterExperience}>{sheetVisible?<div className={styles.letterStage}><button className={styles.stageAction} onClick={()=>setSheetVisible(false)} type="button">{backLabel}</button><LetterPaper {...letter}/></div>:<div className={styles.letterStage}><PostalEnvelope {...envelope} density="reader" onOpen={()=>setSheetVisible(true)}/></div>}</section>}

export function PostalCorrespondenceDialog({title,closeLabel,onClose,children}:{title:string;closeLabel:string;onClose:()=>void;children:ReactNode}){const titleId=useId();const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const element=dialog.current;if(!element)return;if(!element.open)element.showModal();return()=>{if(element.open)element.close()}},[]);return <dialog aria-labelledby={titleId} className={styles.dialog} onCancel={(event)=>{event.preventDefault();onClose()}} onClick={(event)=>{if(event.target===event.currentTarget)onClose()}} ref={dialog}><div className={styles.dialogBody}><button className={styles.close} onClick={onClose} type="button">{closeLabel}</button><h2 id={titleId}>{title}</h2>{children}</div></dialog>}
